# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/irisnet/irishub"
  source = "https://github.com/irisnet/irishub.git"
  version = "=0.7.0"

[[override]]
  name = "github.com/cosmos/cosmos-sdk"
  source = "https://github.com/irisnet/cosmos-sdk.git"
  version = "=v0.26.0-iris0.7.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  source = "https://github.com/irisnet/tendermint.git"
  version = "=v0.26.1-rc0-iris"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "=v1.1"


[prune]
  go-tests = true
  unused-packages = true
