frequency=3
chain="fuxi-6000"
IP="104.198.127.16"



NameFrom = "fuxi"
AddrFrom = "faa106nhdckyf996q69v3qdxwe6y7408pvyvufy0x2"

NameTo = "abc"
AddrTo = "faa1kpyaj0v4vdv9jy8nj0k7w3cnrnvxwvh3hzytdp"


NameFrom2 = "snow"
AddrFrom2 = "faa1kv4y00keqm4zzdelwxudvlps7vmf3ey5mpc6f3"

NameTo2 = "white"
AddrTo2 = "faa1e5vzpw74hfmsmykx0p7ac0cpyn948l8htnkwwq"

NameFrom3 = "dash"
AddrFrom3 = "faa1pagdf9pz7qv6j4dxzgq3a3pmzczaaxcgn7s2dv"

NameTo3 = "board"
AddrTo3 = "faa1p24g58msjnw6m9vqchezvzu3yjzynxwvwj9323"


NameDel = "jerry"
AddrDel = "faa1qsrvxt32d8dpdkmxfzr82c2pfg3j7cam3utqln"

ValFrom = "fva1y359pygp0rnu0e9vp8jz8uq6w5td7sdesaf9z3"
ValTo = "fva1zee2lsmva67a9jx0fy7r5fg3mv5lgzc6eqrg3x"

NameVoter = "iris"
AddrVoter = "faa1nyaaqgc3jjwxm692ufmn0nk5gtk8p6eknjfn0h"
